Table Users {
  id integer [primary key]
  username varchar
  role varchar
  created_at timestamp
}

Table Posts {
  id integer [primary key]
  title varchar
  body text [note: 'Content of the post']
  user_id integer
  status varchar
  created_at timestamp
}

// A one-to-many relationship between users
Table Follows_User_to_Users {
  from_id integer [ref: - Users.id]
  to_id integer [ref: - Users.id]
  created_at timestamp 
}


// A one-to-many relationship between users and posts
Table Owns_User_to_Posts {
  id integer [primary key]
  user_id integer [ref: - Users.id]
  post_id integer [ref: - Posts.id]
}

